# Generated by Django 4.1.5 on 2023-02-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='новый пароль'),
        ),
    ]
