# Generated by Django 4.1.5 on 2023-02-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_new_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_status', 'Can change is_staff')]},
        ),
    ]
