# Generated by Django 4.1.5 on 2023-01-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='message',
        ),
        migrations.AddField(
            model_name='mailing',
            name='add_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customers',
                                    verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='add_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.message',
                                    verbose_name='Сообщение'),
        ),
    ]
