# Generated by Django 4.1.5 on 2023-02-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_customers_user_create_mailing_user_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('turn_off', 'Can turn off mailing')]},
        ),
    ]
